### ISSUE TITLE
Vivecraft 1.16.5 and Fusion [CRASH] More like [Freeze]

### ISSUE THREAD

**Issue by OliverMatt2023** [SuperMartijn642/Fusion#17]
**Version Info**
- Minecraft, 1.16.5
- Fusion, fusion-1.0.6-forge-mc1.16.jar

**Are you using OptiFine:** Yes but with Vivecraft because it is bundled with it.

I am using a Modpack that my friend made... but he refuses to remove ReChiseled and Fusion because of the reason of that I wanted to play in VR on the Modpack, It's 1.16.5, so of course I have Optifine in there since 1.18 and above dropped the dependency of Optifine...

**No Crash log because it just freezes and does not crash.**

Look, I know that you are going to say "Then don't use Optifine" of something like that... But I am playing in VR in a server that I want to play VR in.

**Comment by SuperMartijn642** [comment]
Not much I can do without logs.

It normally already crashes with OptiFine, so my guess is that OptiFine is the cause here as well. OptiFine changes a lot about the game, yet OptiFine is closed source so I can't know what it changes. Because of this, there isn't really a way to fix issues with OptiFine 🤷‍♂️

**Comment by OliverMatt2023** [comment]
So I'm just stuck not playing VR on that server then... Great... Well, Unless Optifine get's their crap together (Which they won't) I can't use VR in 1.16.5...

**Comment by SuperMartijn642** [comment]
Yup, I am afraid so.
