### ISSUE TITLE
[Feature] Add JSON schema

### ISSUE THREAD

**Issue by Pearce-Ropion** [SuperMartijn642/Fusion#40]
**Is your feature request related to a problem? Please describe.**

When editing mcmeta files it would be great to get autocompletion and invalid property/error checking using a JSON schema. For example, when editing vanilla minecraft `mcmeta` files, I use the [minecraft-texture-mcmeta schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/minecraft-texture-mcmeta.json). Which results in autocompletion like this:
<img width="356" alt="Screenshot 2023-12-22 at 10 02 17 AM" src="https://github.com/SuperMartijn642/Fusion/assets/32177944/7501b175-6d9f-4ef5-99f8-32c17f58bfd1">

Alternatively, Here is an example for [Fabric's schema](https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/fabric.mod.json)

**Describe the solution you'd like**

Add a JSON schema either hosted here, or on [SchemaStore](https://www.schemastore.org/json/) that can be referenced when editing fusion enabled `mcmeta` files.

**Comment by SuperMartijn642** [comment]
Schemas for the `pack.mcmeta` file and for the texture metadata are now available in the repository. They're also available from SchemaStore https://github.com/SchemaStore/schemastore/pull/3476.

I couldn't find a schema for the vanilla model format. Since a lot of Fusion's model format is just vanilla stuff, I haven't made a schema for it yet.

**Comment by Pearce-Ropion** [comment]
Great thanks!
