### ISSUE TITLE
[Question] Do I need to modify default resource packs to get connected textures?

### ISSUE THREAD

**Issue by ChTurtles** [SuperMartijn642/Fusion#41]
**Question**
I'm Using the StayTrue resource pack (1.20.1); for some reason, connected/Overlaying textures aren't working. 
Should this work by default or do I need to modify the resource pack to be compatible? I am using a 100+ mod pack so is it possible to have a conflict? 

I'm using Version (Fusion-1.1.0c)

**Comment by SuperMartijn642** [comment]
From googling the StayTrue resource pack, that seems to be a resource pack made for OptiFine. OptiFine's resource pack format is completely different from Fusion's.
You will need to use a resource pack that's made for Fusion.

**Comment by ChTurtles** [comment]
Is there somewhere I can Look at  Fusion compatible resource packs? Everything I can find is made for OptiFine.

**Comment by SuperMartijn642** [comment]
Nope, sadly CurseForge doesn't really have anything to mark which mod is required for a resource pack. The main one I know of is [Midnighttigger's Default Connected Textures](https://www.curseforge.com/minecraft/mc-mods/oculus) because the author told me about it.

There likely also aren't that many resource packs for Fusion as it is relatively new compared to something like OptiFine which has been around forever.
Support for Fusion can also be done in an optional way, so any author should be able to include resources for both Fusion and OptiFine in there resource packs.
