### ISSUE TITLE
Mod is breaking resource pack and minecraft textures

### ISSUE THREAD

**Issue by Matael96** [SuperMartijn642/Fusion#47]
![2024-02-14_02 21 59](https://github.com/SuperMartijn642/Fusion/assets/149072072/9d4ba3f6-e686-42cd-9b80-5fa019083eb7)

After loading RealismMats the game is broken. If i disable the resource pack after enable, the game remains broken. Only restart after disabling the resource pack fixes the problem. I can't run the Minecraft ATM9 Pack with my favorite resource pack because of your mod which is essential for other mods which is very disappointing.

**Comment by SuperMartijn642** [comment]
Please fill in the template. I have no clue what modloader, version of Fusion, or Minecraft version you are using.
What makes you think this is caused by Fusion?

**Comment by Matael96** [comment]
Because when I disable the mod in my custom modpack, the resource pack runs fine. But when I activate it i get the same problem like in the picture. I use Forge 47.2.0 and Minecraft 1.20.1

**Comment by SuperMartijn642** [comment]
Realism Mats appears to be a paid resource pack. I cannot test this as I don't have access to it.
If you have another resource pack with which I can reproduce the issue, let me know.

Additionally, I can't imagine there being an issue for one specific resource pack and other resource packs seem to work just fine. Are you sure this is caused by Fusion? Are there no other mods needed to reproduce the issue?
