### ISSUE TITLE
[Bug] folders named fusion in resource packs cause Fusion to break

### ISSUE THREAD

**Issue by steelphoenix4** [SuperMartijn642/Fusion#85]
**Version Info**
- Minecraft, 1.20.1
- Fusion, 1.1.1

**Are you using OptiFine:** No

**Description of the Bug**
Models stop loading, resulting in random blocks having missing textures.

**Steps to Reproduce**
Create a Fusion resource pack with a folder in the models folder named "fusion".

**Screenshots**
![image](https://github.com/user-attachments/assets/e3d4898f-eea3-4e63-b47d-7cbab0160eda)
![image](https://github.com/user-attachments/assets/1b281487-626b-4ece-889f-4758b4f5413f)
![image](https://github.com/user-attachments/assets/d5d0dbe0-bdc2-48d4-b2d3-68e882a4c032)
Nothing was changed between screenshots, just f3+t resource pack reloads.

[latest.log](https://github.com/user-attachments/files/17267983/latest.log)

**Comment by SuperMartijn642** [comment]
> Failed to load model mekanismgenerators:models/block/fusion/port.json
Invalid json for predicate type 'fusion:match_block'!
Unknown block 'mekanismgenerators:reactor_frame'!

> Failed to load model mekanismgenerators:models/block/fusion/frame.json
Invalid json for predicate type 'fusion:match_block'!
Unknown block 'mekanismgenerators:reactor_port'!

The log does show some errors in the model jsons for some of the models. Are you sure `mekanismgenerators:reactor_frame` and `mekanismgenerators:reactor_port` are the correct registry names for the blocks you want?

My guess is that when a model fails to load due to a valid error in the model json, like the incorrect block ids above, it for some reason breaks future loading. Since models are not loaded in a particular order, that might explain why it seems to break random models each time when reloading resources. Pretty sure it has nothing to do with the folder name though.

**Comment by steelphoenix4** [comment]
Apologies, apparently I am very bad at isolating problems. You are correct the name of the block was not in fact  
`mekanismgenerators:reactor_frame` but  `mekanismgenerators:fusion_reactor_frame`. Everything works as intended.

**Comment by SuperMartijn642** [comment]
Of course the weird random broken models is not ideal, but I am redoing a large part of the mod anyways, so we'll have to see after that.
